name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "enhancement"
  - title: "⚡ Fixes"
    labels:
      - "fix"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
autolabeler:
  - label: "enhancement"
    branch:
      - '/feat\/.+/'
  - label: "fix"
    branch:
      - '/fix\/.+/'
    title:
      - "/fix/i"
  - label: "chore"
    branch:
      - '/chore\/.+/'
change-title-escapes: '\<*_&'
exclude-labels:
  - "exclude from changelog"
template: |
  ## Changes

  $CHANGES
