name: Draft next release

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          # Due to the limitation of GitHub workflows, need to use a personal access token to trigger the event for tag creation.
          GITHUB_TOKEN: ${{ secrets.PAT }}
