name: Release

on:
  push
  # push:
  #   tags:
  #     - "v[0-9].[0-9]+.[0-9]+"
  # release:
  #   types: [created]

jobs:
  release_with_artifacts:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - run: echo 'hey'
      # - uses: actions/checkout@v2
      # - uses: actions/setup-node@v1
      #   with:
      #     node-version: 16.x
      # - run: npm install
      # - run: npm run package
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - uses: softprops/action-gh-release@v1
      #   with:
      #     files: |
      #       packages/*.exe
      #       packages/*.dmg
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
