name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  upload_artifacts:
    needs: update_release_draft
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - name: Get release
        id: latest_release_info
        uses: jossef/action-latest-release-info@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo hey
      - uses: actions/checkout@v2
      - name: Upload release binary
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.latest_release_info.outputs.upload_url }}
          asset_path: ./index.html.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
