name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.get_release.outputs.upload_url }}
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get release
        id: get_release
        uses: jossef/action-latest-release-info@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  upload_artifacts:
    needs: update_release_draft
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - run: echo hey
      # - run: echo ${{ needs.update_release_draft.outputs.outputs1 }}
      # - uses: actions/checkout@v2
      # - name: Upload release binary
      #   uses: actions/upload-release-asset@v1.0.2
      #   with:
      #     upload_url: ${{ needs.update_release_draft.outputs.outputs1 }}
      #     asset_path: ./index.html.zip
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
