name: Action Sample

on:
  push:
    tags:
      - "v[0-9].[0-9]+.[0-9]+"

jobs:
  build_and_upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
      - name: Build application
        run: npm run package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cleanup artifacts
        run: npx rimraf "packages/!(*.exe|*.dmg)"
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}
          path: packages
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: "packages/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
