name: Upload artifacts to the latest release note

on:
  push:
    tags:
      - "v[0-9].[0-9]+.[0-9]+"

jobs:
  upload_artifacts:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - name: Get release info for later use
        id: release_info
        uses: jossef/action-latest-release-info@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm install
      - name: Build app
        run: npm run package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get version number
        id: version_number
        uses: bhowell2/github-substring-action@v1.0.0
        with:
          value: ${{ steps.release_info.outputs.tag_name }}
          index_of_str: "v"
      - name: Upload artifact on Windows
        if: matrix.os == 'windows-latest'
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.release_info.outputs.upload_url }}
          asset_path: ./packages/LaLaLa Setup ${{ steps.version_number.outputs.substring }}.exe
          asset_name: LaLaLa_${{ steps.release_info.outputs.tag_name }}.exe
          asset_content_type: application/x-msdownload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact on Mac
        if: matrix.os == 'macos-latest'
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.release_info.outputs.upload_url }}
          asset_path: ./packages/LaLaLa-${{ steps.version_number.outputs.substring }}.dmg
          asset_name: LaLaLa_${{ steps.release_info.outputs.tag_name }}.dmg
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
